apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{namespace}}
data:
  default.conf: |   
    server {
      listen 80;
  
      location / {
        proxy_pass http://flask-service:8080/index.html;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: {{namespace}}
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: nginx
    spec:
    volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      containers:
      - name: nginx-container
        image: nginx:alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: {{namespace}}
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 80
