apiVersion: v1
kind: Namespace
metadata: 
  name: {{namespace}}
  labels: 
    name: {{namespace}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api-app
  namespace: {{namespace}}
  labels:
    app: python-api-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: python-api-app
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: python-api-app
    spec:
      containers:
      - name: python-api-app-container
        image: debushee/python-api-app-kubernetes:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: python-api-app-service
  namespace: {{namespace}}
spec:
  type: ClusterIP
  selector:
    app: python-api-app
  ports:
  - protocol: TCP
    port: 8080
